In [1]:
import pandas as pd

In [2]:
df=pd.Series([10,20,30,40])
print(df)

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
df=pd.Series([10,22,31,90,89], index=["a","b","c","d","e"])
print(df)

a    10
b    22
c    31
d    90
e    89
dtype: int64

In [14]:
student={
    "Ram":98,
    "sham":97,
    "miku":67
}
print(student)
df=pd.Series(student)
print(df)
print(df["Ram"])

{'Ram': 98, 'sham': 97, 'miku': 67}
Ram     98
sham    97
miku    67
dtype: int64
98

In [19]:
student={
    "ram":90,
    "sham":78,
    "madam":65,
    "miku":89
}
print(student)
s=pd.Series(student)
print(s)
print(s.index)
print(s.values)
print(s.dtype)
print(s.shape)
print(s.size)
print(s+10)
print(s*2)

{'ram': 90, 'sham': 78, 'madam': 65, 'miku': 89}
ram      90
sham     78
madam    65
miku     89
dtype: int64
Index(['ram', 'sham', 'madam', 'miku'], dtype='str')
[90 78 65 89]
int64
(4,)
4
ram      100
sham      88
madam     75
miku      99
dtype: int64
ram      180
sham     156
madam    130
miku     178
dtype: int64

In [25]:
num=pd.Series([11,23,98,67,45,34,88,66,55,34])
print(max(num))
print(min(num))
print(num*5)
print(num+100)
num[num%2==0]=0
print(num)

98
11
0     55
1    115
2    490
3    335
4    225
5    170
6    440
7    330
8    275
9    170
dtype: int64
0    111
1    123
2    198
3    167
4    145
5    134
6    188
7    166
8    155
9    134
dtype: int64
0    11
1    23
2     0
3    67
4    45
5     0
6     0
7     0
8    55
9     0
dtype: int64

In [27]:
data={
    "Name":["Ram","Sham","Rita"],
    "Age":[22,25,21],
    "Salary":[45000,65000,87000]
}
df=pd.DataFrame(data,index=["a","b","c"])
print(df)

   Name  Age  Salary
a   Ram   22   45000
b  Sham   25   65000
c  Rita   21   87000

In [37]:
student=[
    ["ram",9],
    ["sham",78],
    ["goli",34]
]
df=pd.DataFrame(student,columns=["name","age"])
print(df)
print(df.head(1))

   name  age
0   ram    9
1  sham   78
2  goli   34
  name  age
0  ram    9

In [44]:
student={
    "name":["sham"],
    "marks":[90],
    "salary":[7860],
    "age":[23]
}
df=pd.DataFrame(student)
print(df)

   name  marks  salary  age
0  sham     90    7860   23

In [58]:
student={
    "s1":{
        "name":"radha",
        "age":22,
        "sub":"english"
    },
    "s2":{
        "name":"flic",
        "age":28,
        "sub":"spain"
    },
    "s3":{
        "name":"sam",
        "age":32,
        "sub":"hindi"
    }
}
df=pd.DataFrame(student)
print(df)
df.tail(2)
df.head()
df.columns
df.index

           s1     s2     s3
name    radha   flic    sam
age        22     28     32
sub   english  spain  hindi

Index(['name', 'age', 'sub'], dtype='str')

In [64]:
s=pd.Series([12,34,67,89,90],index=["a","b","c","d","e"])
print(s)

a    12
b    34
c    67
d    89
e    90
dtype: int64

In [69]:
student={
    "ram":89,
    "sham":90,
    "rita":67
}
s=pd.Series(student)
print(s)
print(student)
print(s["ram"])

ram     89
sham    90
rita    67
dtype: int64
{'ram': 89, 'sham': 90, 'rita': 67}
89

In [74]:
student={
    "ram":76,
    "sita":90,
    "vaibhav":67
}
s=pd.Series(student)
print(s)
print(s.index)
print(s.values)
print(s.dtype)
print(s.size)
print(s.shape)
print(s+100)
print(s*3)

ram        76
sita       90
vaibhav    67
dtype: int64
Index(['ram', 'sita', 'vaibhav'], dtype='str')
[76 90 67]
int64
3
(3,)
ram        176
sita       190
vaibhav    167
dtype: int64
ram        228
sita       270
vaibhav    201
dtype: int64

In [90]:
data={
    "Name":["ram","sham","rita"],
    "age":[22,34,56],
    "salary":[78000,45000,87000]
}
df=pd.DataFrame(data)

df.memory_usage()
df.head(3)
df["salary"]

0    78000
1    45000
2    87000
Name: salary, dtype: int64

In [102]:
data={
    "name":["ram","sham","rita"],
    "age":[34,76,23],
    "salary":[4500,8700,5700]
}
df=pd.DataFrame(data)


df.loc[0:2]

   name  age  salary
0   ram   34    4500
1  sham   76    8700
2  rita   23    5700

In [107]:
data={
    "name":["ram","sham","rita"],
    "age":[34,76,23],
    "salary":[4500,8700,5700]
}
df=pd.DataFrame(data)

df[df["salary"]>5700]
df[(df["age"]>22) & (df["salary"]>5000)]
df[df["name"].isin(["ram","rita"])]

   name  age  salary
0   ram   34    4500
2  rita   23    5700

In [119]:
data={
    "name":["ram","sham","rita"],
    "age":[34,76,23],
    "salary":[4500,8700,5700]
}
df=pd.DataFrame(data)
df.sort_values("salary" ,ascending=False)
df.sort_values(["salary","age"])
df.dropna()

   name  age  salary
0   ram   34    4500
1  sham   76    8700
2  rita   23    5700

In [131]:
data={
    "name":["ram","sham","rita"],
    "age":[34,76,23],
    "salary":[4500,8700,5700]
}
df=pd.DataFrame(data)
# df.sort_values("salary" ,ascending=False)
# df.sort_values(["salary","age"])
# df.fillna(0)
df.fillna(df["salary"].mean())
df.duplicated()
# df.drop_duplicates()
df.rename(columns={"salary":"income"})
df.drop("salary",axis=1)

   name  age
0   ram   34
1  sham   76
2  rita   23

In [145]:
data={
    "name":["ram","sham","rita"],
    "age":[34,76,23],
    "salary":[4500,8700,5700]
}
df=pd.DataFrame(data)
print(df)
df["name"].str.upper()
df["name"].str.lower()
df["name"].str.title()
df["name"].str.contains("a")
df["name"].str.replace("ram","ramesh")
print(df)

   name  age  salary
0   ram   34    4500
1  sham   76    8700
2  rita   23    5700
   name  age  salary
0   ram   34    4500
1  sham   76    8700
2  rita   23    5700

KeyError: 'Date'